default:
  image:
    name: python:latest

before_script:
  - pip install -q --no-cache-dir --progress-bar off "poetry==1.6.1" 
  - poetry install 

test-coverage:
  stage: test
  script:
    - poetry run coverage run -m pytest --verbose --continue-on-collection-errors 
    - find . -type f -name "*.py" | xargs -t coverage report

lint:
  stage: test
  script:
    - poetry run ruff format --check .
    - poetry run ruff check .

type-check:
  stage: test
  script: 
    - poetry run mypy src/