default:
  image:
    name: python:latest

before_script:
  - pip install -q --no-cache-dir --progress-bar off "poetry==1.6.1" 
  - poetry install 

test-coverage:
  stage: test
  script:
    - poetry run coverage run -m pytest --verbose --continue-on-collection-errors 
    - poetry run coverage report -m

lint:
  stage: test
  script:
    - poetry run ruff format
    - poetry run ruff format --check

type-check:
  stage: test
  script: 
    - poetry run mypy .